services:
  db:
    image: postgres:16-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    # bin/dev roda o Foreman/Tailwind em paralelo com o servidor Rails
    command: bin/dev
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres_data: